### ISSUE TITLE
Update Gatsby sample project to use new plugin

### ISSUE THREAD

**Issue by mshick** [takeshape/takeshape-gatsby#26]
## Description

The current Gatsby sample project should use the new plugin. Maybe it should also be moved here and set up as a Gatsby starter? If so, let's link from the old sample to this new project and some instructions.

## Tasks

- [x] Review existing sample project
- [x] Copy to a new package here
- [x] Add any necessary Gatsby starter packaging
- [x] Update documentation on old sample
- [x] Ensure good docs on new sample
