### ISSUE TITLE
Review starter workflow and docs

### ISSUE THREAD

**Issue by mshick** [takeshape/takeshape-gatsby#27]
## Description

The workflow to use the new Gatsby starter and plugin should be reviewed for sanity.

## Tasks

- [x] Follow instructions here to set up a starter project: https://github.com/takeshape/gatsby-starter-takeshape-portfolio
- [x] Follow instructions here to set up a bare bones project: https://github.com/takeshape/takeshape-gatsby/tree/trunk/packages/gatsby-source-takeshape
- [x] Report back any inconsistencies or problems encountered
- [x] Update docs if needed

@allanlasser please take a look!

**Comment by allanlasser** [comment]
I encountered an error during the `npx` project setup, at the very end when it tries to `cd` into the new `portfolio` directory:

<img width="962" alt="Screen Shot 2020-08-31 at 5 58 51 PM" src="https://user-images.githubusercontent.com/6089482/91773008-ef9df000-ebb3-11ea-921d-b7eb7e6b444f.png">

**Comment by allanlasser** [comment]
Upon running `yarn start` for the first time, I got a GraphQL error. The entire build is below.

I also consistently get `TypeError: data.takeshape.about.socialProfiles is null` when viewing the site at `localhost:8000`. I believe this is because `src/components/menu.js:48` calls `data.takeshape.about.socialProfiles.map`, but the socialProfiles in the project created from the pattern is created empty. The same goes for the optional `socialProfile.socialNetworkIcon` property.

Based on looking at the pattern included in the starter, it seems as though data _should_ be included along with the project when it's added, no? Is this potentially an import bug?

```bash
$ yarn start
yarn run v1.22.4
$ npm run develop
npm WARN lifecycle The node binary used for scripts is /var/folders/jf/2n5798nn5p59r9rn412_3ggr0000gn/T/yarn--1598911629174-0.6041167093416828/node but npm is using /Users/allan/.nvm/versions/node/v12.16.1/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> gatsby-starter-takeshape-portfolio@1.0.0 develop /Users/allan/Developer/takeshape/portfolio
> npm run clean && gatsby develop

npm WARN lifecycle The node binary used for scripts is /var/folders/jf/2n5798nn5p59r9rn412_3ggr0000gn/T/yarn--1598911629174-0.6041167093416828/node but npm is using /Users/allan/.nvm/versions/node/v12.16.1/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> gatsby-starter-takeshape-portfolio@1.0.0 clean /Users/allan/Developer/takeshape/portfolio
> gatsby clean

info Deleting .cache, public,
info Successfully deleted directories
success open and validate gatsby-configs - 0.040s
success load plugins - 3.042s
success onPreInit - 0.052s
success initialize cache - 0.012s
success copy gatsby files - 0.067s
success onPreBootstrap - 0.012s
success createSchemaCustomization - 0.007s
info [takeshape] Fetching remote schema
success Checking for changed pages - 0.002s
success source and transform nodes - 1.297s
success building schema - 0.205s
success createPages - 0.267s
success Checking for changed pages - 0.002s
success createPagesStatefully - 0.068s
success update schema - 0.025s
success write out redirect data - 0.005s
info [takeshape] Update channel connected
success Build manifest and related icons - 0.138s
success onPostBootstrap - 0.144s
info bootstrap finished - 8.332s
success onPreExtractQueries - 0.005s
success extract queries from components - 0.352s
warn The GraphQL query in the non-page component
Exported queries are only executed for Page components. It's possible you're
trying to create pages in your gatsby-node.js and that's failing for some
reason.

If the failing component(s) is a regular component and not intended to be a page
component, you generally want to use a <StaticQuery> (https://gatsbyjs.org/docs/static-query)
instead of exporting a page query.

If you're more experienced with GraphQL, you can also export GraphQL
fragments from components and compose the fragments in the Page component
query and pass data down into the child component — https://graphql.org/learn/queries/#fragments
success write out requires - 0.033s

 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Not authorized to perform content:create on ts:content:8e494979-4f6d-4e02-b136-f34610feecbb:default:S1oNHDYc7:*:*

   9 |   width
  10 | }
  11 |
  12 | query usersallanDevelopertakeshapeportfoliosrccomponentsmenuJs1432955340 {
  13 |   takeshape {
  14 |     projects: getProjectList {
  15 |       items {
  16 |         name
  17 |       }
  18 |     }
> 19 |     about: getAbout {
     |     ^
  20 |       socialProfiles {
  21 |         profileUrl
  22 |         socialNetwork
  23 |         socialNetworkIcon {
  24 |           path
  25 |           fixed {
  26 |             ...GatsbyTakeShapeImageFixed
  27 |           }
  28 |         }
  29 |       }

File path: /Users/allan/Developer/takeshape/portfolio/src/components/menu.js
Plugin: none

success run static queries - 0.316s - 1/1 3.17/s

 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Not authorized to perform content:create on ts:content:8e494979-4f6d-4e02-b136-f34610feecbb:default:S1oNHDYc7:*:*

   4 |   height
   5 |   src
   6 |   srcSet
   7 |   srcWebp
   8 |   srcSetWebp
   9 |   width
  10 | }
  11 |
  12 | query usersallanDevelopertakeshapeportfoliosrcpagesaboutJs3545070286 {
  13 |   takeshape {
> 14 |     about: getAbout {
     |     ^
  15 |       biography: biographyHtml
  16 |       portrait {
  17 |         title
  18 |         description
  19 |         path
  20 |         fixed(height: 150, width: 150) {
  21 |           ...GatsbyTakeShapeImageFixed
  22 |         }
  23 |       }
  24 |     }

File path: /Users/allan/Developer/takeshape/portfolio/src/pages/about.js
Url path: /about/
Plugin: none

success run page queries - 0.211s - 5/5 23.71/s
⠀
You can now view gatsby-starter-takeshape-portfolio in the browser.
⠀
  http://localhost:8000/
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and schema
⠀
  http://localhost:8000/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use gatsby build
```

**Comment by mshick** [comment]
ah, okay, maybe there's a problem with the pattern... ty!

**Comment by mshick** [comment]
@allanlasser I've updated the patterns. Do you mind trying again?

I'd also be curious if you encounter issues right after the import where you can't access the newly created project for a few minutes...

**Comment by allanlasser** [comment]
That must've done it, I was able to go start from finish without a hitch! I haven't hit the delay issue you mentioned, but I'll keep my eye open for it.

I opened a PR on the sample project to update the language on some of the README steps: https://github.com/takeshape/gatsby-starter-takeshape-portfolio/pull/1

**Comment by allanlasser** [comment]
The instructions for the from-scratch plugin usage were very clear. I didn't encounter any problems, but I did think that the ".env" section might benefit from being higher up in the README, closer to the `gatsby-config` setup. Very minor, tho!

**Comment by mshick** [comment]
Moved it up, makes sense!
